name: Flutter Chat Workshop

type: flutter

steps:
  - name: Introduction
    directory: 01_introduction
    has_solution: false
  - name: Initialize App
    directory: 02_run_application
    has_solution: true
  - name: Prepare App
    directory: 03_prepare_app
    has_solution: true
  - name: First Page
    directory: 04_first_page
    has_solution: true
  - name: Setup Layout
    directory: 05_setup_layout
    has_solution: true
  - name: Chat List
    directory: 06_chat_list
    has_solution: true
  - name: Stateful Widget
    directory: 07_stateful_widget
    has_solution: true
  - name: Write Message
    directory: 08_write_message
    has_solution: true
  - name: Firebase Integration
    directory: 09_firebase_integration
    has_solution: true
